// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp4UCWTu1AlP0RWLyCPBifYJu4ewaBykE',
    appId: '1:166873146454:web:ac1e9429c919f8997147f7',
    messagingSenderId: '166873146454',
    projectId: 'electiva-8fb97',
    authDomain: 'electiva-8fb97.firebaseapp.com',
    storageBucket: 'electiva-8fb97.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiS6pqhUmDaz3VrAxKktzpGoRAyEotTHg',
    appId: '1:166873146454:android:05128fff0f08abc67147f7',
    messagingSenderId: '166873146454',
    projectId: 'electiva-8fb97',
    storageBucket: 'electiva-8fb97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChHaBDvkq19VQEeYpvLQOcp9a2YyeWhyc',
    appId: '1:166873146454:ios:9e6995a566f242fa7147f7',
    messagingSenderId: '166873146454',
    projectId: 'electiva-8fb97',
    storageBucket: 'electiva-8fb97.firebasestorage.app',
    iosBundleId: 'com.example.grupo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChHaBDvkq19VQEeYpvLQOcp9a2YyeWhyc',
    appId: '1:166873146454:ios:9e6995a566f242fa7147f7',
    messagingSenderId: '166873146454',
    projectId: 'electiva-8fb97',
    storageBucket: 'electiva-8fb97.firebasestorage.app',
    iosBundleId: 'com.example.grupo2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp4UCWTu1AlP0RWLyCPBifYJu4ewaBykE',
    appId: '1:166873146454:web:fa59e6818cf755767147f7',
    messagingSenderId: '166873146454',
    projectId: 'electiva-8fb97',
    authDomain: 'electiva-8fb97.firebaseapp.com',
    storageBucket: 'electiva-8fb97.firebasestorage.app',
  );
}
